# Stock mutations
mutation CreateStock($input: StockInput!) {
  createStock(input: $input) {
    id
    symbol
    name
    price
    change
    changePercent
  }
}

mutation UpdateStock($id: ID!, $input: StockInput!) {
  updateStock(id: $id, input: $input) {
    id
    symbol
    name
    price
    change
    changePercent
  }
}

# News mutations
mutation CreateNewsArticle($input: NewsArticleInput!) {
  createNewsArticle(input: $input) {
    id
    title
    content
    publishedAt
    stockId
  }
}

mutation UpdateNewsArticle($id: ID!, $input: NewsArticleInput!) {
  updateNewsArticle(id: $id, input: $input) {
    id
    title
    content
    publishedAt
    stockId
  }
}
