# Codemagic CI/CD configuration for AI Stock Summary (MarketMind AI)
# This workflow builds and deploys the Flutter iOS app to App Store Connect
#
# Build root: Repository root (not mobile-app)
# All scripts run from the repository root unless working_directory is specified

definitions:
  env_versions: &env_versions
    flutter: stable
    xcode: latest
    cocoapods: default

  scripts:
    - &preflight_checks
      name: Preflight checks (Firebase config validation)
      script: |
        echo "🔍 Running preflight checks..."
        
        # Check GoogleService-Info.plist exists
        PLIST_PATH="mobile-app/ios/Runner/GoogleService-Info.plist"
        if [ ! -f "$PLIST_PATH" ]; then
          echo "❌ ERROR: GoogleService-Info.plist NOT FOUND at $PLIST_PATH"
          exit 1
        fi
        echo "✅ GoogleService-Info.plist exists"
        
        # Extract and display plist info
        PROJECT_ID=$(grep -A1 'PROJECT_ID' "$PLIST_PATH" | grep string | sed 's/.*<string>\(.*\)<\/string>.*/\1/')
        PLIST_BUNDLE_ID=$(grep -A1 'BUNDLE_ID' "$PLIST_PATH" | grep string | sed 's/.*<string>\(.*\)<\/string>.*/\1/')
        echo "   PROJECT_ID: $PROJECT_ID"
        echo "   BUNDLE_ID: $PLIST_BUNDLE_ID"
        
        # Verify bundle ID matches
        if [ "$PLIST_BUNDLE_ID" != "com.marketmindai" ]; then
          echo "⚠️ WARNING: Bundle ID mismatch! Expected: com.marketmindai, Got: $PLIST_BUNDLE_ID"
        fi
        
        # Check firebase_options.dart exists
        OPTIONS_PATH="mobile-app/lib/firebase_options.dart"
        if [ ! -f "$OPTIONS_PATH" ]; then
          echo "❌ ERROR: firebase_options.dart NOT FOUND at $OPTIONS_PATH"
          exit 1
        fi
        echo "✅ firebase_options.dart exists"
        
        # Verify plist is in Xcode project
        if grep -q "GoogleService-Info.plist in Resources" mobile-app/ios/Runner.xcodeproj/project.pbxproj; then
          echo "✅ GoogleService-Info.plist is in Copy Bundle Resources"
        else
          echo "❌ ERROR: GoogleService-Info.plist NOT in Copy Bundle Resources!"
          exit 1
        fi
        
        echo "✅ All preflight checks passed"

    - &clean_flutter
      name: Clean Flutter
      script: |
        cd mobile-app
        flutter clean

    - &get_packages
      name: Get Flutter packages
      script: |
        cd mobile-app
        flutter pub get

    - &install_pods
      name: Install CocoaPods dependencies
      script: |
        cd mobile-app/ios
        rm -rf Pods Podfile.lock
        pod install --repo-update

    - &flutter_analyze
      name: Run Flutter analyze
      script: |
        cd mobile-app
        flutter analyze --no-fatal-infos
      ignore_failure: true

    - &flutter_test
      name: Run Flutter tests
      script: |
        cd mobile-app
        flutter test
      ignore_failure: true

workflows:
  # ============================================================================
  # iOS App Store Release Workflow
  # ============================================================================
  ios-release:
    name: iOS App Store Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    
    integrations:
      app_store_connect: codemagic
    
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.marketmindai
      vars:
        BUNDLE_ID: com.marketmindai
        APP_STORE_APP_ID: "6756526355"
      <<: *env_versions
    
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: main
          include: true
          source: true
        - pattern: release/*
          include: true
          source: true
      tag_patterns:
        - pattern: 'v*'
          include: true
    
    scripts:
      - name: Set up local properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/mobile-app/android/local.properties"

      - *preflight_checks

      - *clean_flutter
      
      - *get_packages
      
      - name: Prepare iOS build
        script: |
          cd mobile-app
          flutter precache --ios
          flutter build ios --config-only --release --no-codesign
      
      - *install_pods
      
      - name: Set up code signing
        script: |
          xcode-project use-profiles --project=mobile-app/ios/Runner.xcodeproj
      
      - name: Increment build number
        script: |
          # Ensure PROJECT_BUILD_NUMBER is set and numeric
          BUILD_NUM=${PROJECT_BUILD_NUMBER:-1}
          NEW_BUILD_NUM=$((BUILD_NUM + 1))
          echo "Setting build number to: $NEW_BUILD_NUM"
          agvtool new-version -all $NEW_BUILD_NUM
        working_directory: mobile-app/ios
      
      - name: Build iOS IPA
        script: |
          cd mobile-app
          flutter build ipa \
            --release \
            --export-options-plist=/Users/builder/export_options.plist
      
      - name: Verify IPA contents
        script: |
          echo "🔍 Verifying IPA contents..."
          IPA_PATH=$(find mobile-app/build/ios -name "*.ipa" -type f | head -1)
          
          if [ -n "$IPA_PATH" ]; then
            echo "   Found IPA: $IPA_PATH"
            TEMP_DIR=$(mktemp -d)
            unzip -q "$IPA_PATH" -d "$TEMP_DIR"
            APP_PATH=$(find "$TEMP_DIR" -name "*.app" -type d | head -1)
            
            if [ -f "$APP_PATH/GoogleService-Info.plist" ]; then
              echo "✅ GoogleService-Info.plist IS in the IPA"
            else
              echo "❌ ERROR: GoogleService-Info.plist NOT in IPA!"
              ls -la "$APP_PATH/" | head -20
              exit 1
            fi
            rm -rf "$TEMP_DIR"
          else
            echo "⚠️ IPA not found for verification"
          fi
    
    artifacts:
      - mobile-app/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      email:
        recipients:
          - erolrony91@gmail.com
        notify:
          success: true
          failure: true
      
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
        expire_build_submitted_for_review: true
        beta_groups:
          - Internal Testers

  # ============================================================================
  # iOS Development/Testing Workflow
  # ============================================================================
  ios-development:
    name: iOS Development Build
    max_build_duration: 90
    instance_type: mac_mini_m2
    
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.marketmindai
      <<: *env_versions
    
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    
    scripts:
      - *preflight_checks
      - *clean_flutter
      - *get_packages
      
      - name: Prepare iOS build
        script: |
          cd mobile-app
          flutter precache --ios
          flutter build ios --config-only --debug --no-codesign
      
      - *flutter_analyze
      - *flutter_test
      - *install_pods
      
      - name: Set up code signing
        script: |
          xcode-project use-profiles --project=mobile-app/ios/Runner.xcodeproj
      
      - name: Build iOS app (Debug)
        script: |
          cd mobile-app
          flutter build ios --debug --no-codesign
    
    artifacts:
      - mobile-app/build/ios/iphoneos/*.app
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      email:
        recipients:
          - erolrony91@gmail.com
        notify:
          success: false
          failure: true

  # ============================================================================
  # Android Release Workflow
  # ============================================================================
  android-release:
    name: Android Play Store Release
    max_build_duration: 90
    instance_type: linux_x2
    
    environment:
      android_signing:
        - ai_stock_keystore
      groups:
        - google_play
      <<: *env_versions
    
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: main
          include: true
          source: true
      tag_patterns:
        - pattern: 'v*'
          include: true
    
    scripts:
      - name: Set up local properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/mobile-app/android/local.properties"
      
      - *get_packages
      - *flutter_analyze
      
      - name: Build Android App Bundle
        script: |
          cd mobile-app
          flutter build appbundle --release
    
    artifacts:
      - mobile-app/build/app/outputs/bundle/release/*.aab
      - mobile-app/build/app/outputs/flutter-apk/*.apk
    
    publishing:
      email:
        recipients:
          - erolrony91@gmail.com
        notify:
          success: true
          failure: true
      
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
