# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter CI (mobile-app)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  flutter-mobile-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Flutter pub get
        working-directory: mobile-app
        run: flutter pub get

      - name: Flutter analyze
        continue-on-error: true
        working-directory: mobile-app
        run: flutter analyze

      - name: Flutter tests
        working-directory: mobile-app
        run: flutter test
