name: Deploy to Play Store

on:
  workflow_dispatch:
    inputs:
      track:
        description: 'Release track'
        required: true
        default: 'internal'
        type: choice
        options:
        - internal
        - alpha
        - beta
        - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
        
    - name: Install backend dependencies
      run: |
        cd backend
        npm ci
        
    - name: Auto-increment version
      id: version
      run: |
        cd backend
        NEW_VERSION=$(node scripts/auto-increment-version.js)
        echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
        echo "✅ New version: $NEW_VERSION"
        
    - name: Validate secrets
      shell: bash
      run: |
        required=(UPLOAD_KEYSTORE_BASE64 KEYSTORE_PASSWORD KEY_ALIAS KEY_PASSWORD GOOGLE_SERVICES_JSON PLAY_CONSOLE_SA_JSON)
        for s in "${required[@]}"; do
          if [ -z "${!s}" ]; then echo "Missing secret: $s"; exit 1; fi
        done
      env:
        UPLOAD_KEYSTORE_BASE64: ${{ secrets.UPLOAD_KEYSTORE_BASE64 }}
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        PLAY_CONSOLE_SA_JSON: ${{ secrets.PLAY_CONSOLE_SA_JSON }}

    - name: Setup Android signing
      if: success()
      run: |
        cd mobile-app/android
        echo "${{ secrets.UPLOAD_KEYSTORE_BASE64 }}" | base64 --decode > app/upload-keystore.jks
        printf "storeFile=upload-keystore.jks\nstorePassword=%s\nkeyAlias=%s\nkeyPassword=%s\n" \
          "${{ secrets.KEYSTORE_PASSWORD }}" "${{ secrets.KEY_ALIAS }}" "${{ secrets.KEY_PASSWORD }}" > key.properties
        
    - name: Setup Firebase config
      run: |
        cd mobile-app/android/app
        echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > google-services.json
        
    - name: Build AAB
      run: |
        cd mobile-app
        flutter pub get
        flutter build appbundle --release --no-tree-shake-icons
        
    - name: Setup Play Console service account
      run: |
        echo "${{ secrets.PLAY_CONSOLE_SA_JSON }}" | base64 -d > play-console-sa.json
        
    - name: Upload to Play Store
      run: |
        cd backend
        TRACK="${{ github.event.inputs.track || 'internal' }}"
        node scripts/upload-to-play.js com.ai_stock_summary ../mobile-app/build/app/outputs/bundle/release/app-release.aab ../play-console-sa.json $TRACK
        
    - name: Commit version bump
      if: success()
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add mobile-app/pubspec.yaml
        git commit -m "chore: bump version to ${{ steps.version.outputs.new_version }}" || exit 0
        git push
